language: node_js
node_js:
- "10"
cache:
 npm: true
  directories:
  - node_modules
  # we also need to cache folder with Cypress binary
  - ~/.cache
install:
- npm install -q --no-color --no-progress
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
install:
- npm ci
script:
- npm run test -- --coverage
- $(npm bin)/cypress run --record
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

 